#!/usr/bin/env ruby

require 'bundler/setup'

require 'pathname'

require 'trollop'
require 'colorize'

opts = Trollop::options do

    opt :file, "What file to watch",
        :type => :string,
        :required => true

    opt :exec, "Run command from your path",
        :type => :string,
        :default => "rake"

    opt :delay, "How often to compare timestamps (seconds)",
        :type => :int,
        :default => 3
end

class Executor

    attr_reader :delay

    # No longer checking that the variable is populated because trollop gem
    # adds required and default options

    def initialize args

        @watch = args[:file].to_s
        @watch_full = Pathname.new(@watch).realpath


        @run = args[:exec].to_s
        @delay = args[:delay].to_i

        self.inform

    end

    def inform
        puts "Moar version 0.1".colorize(:light_white)
        puts "Type q + Enter to quit"
        print " * ".colorize(:light_red)
        puts "Checking every #{@delay} seconds"
        print " * ".colorize(:light_red)
        puts "Watching #{@watch_full}"
        print " * ".colorize(:light_red)
        puts "Running #{@run} upon changes"
        print "moar> ".colorize(:yellow)
    end

    def onchange
        system("clear")
        system("#{@run}")

        puts ''
        puts "...done. Still watching..."
        print "moar> ".colorize(:yellow)
    end

    def timestamp

        File.mtime(@watch_full)

#        begin
#        File.mtime(@watch_full)
#
#        rescue Errno::ENOENT => e
#            puts "Err: Attempted timestamp-chk while file was being saved".colorize(:red)
#            puts "Running command in #{@delay} seconds..."
#            sleep delay
#
#            timestamp
#        end

    end

    def before
        @time_before = self.timestamp
    end

    def after
        @time_after = self.timestamp
    end

    def check
        self.onchange if @time_before != @time_after
    end

end

Thread.new do

    while line = STDIN.gets
        break if line.chomp == 'q'
    end

    exit
end

main = Executor.new opts

loop do
    main.before
    sleep main.delay
    main.after
    main.check
end
