#!/usr/bin/env ruby

require 'bundler/setup'

require 'pathname'

require 'trollop'
require 'colorize'

opts = Trollop::options do

    opt :file, "What file to watch",
        :type => :string,
        :required => true
    
    opt :exec, "Run command from your path",
        :type => :string,
        :default => "rake"

    opt :delay, "How often to compare timestamps (seconds)",
        :type => :int,
        :default => 3
end

class Executor

    attr_reader :delay

    def initialize args

        @watch = args[:file].to_s
        @watch_full = Pathname.new(@watch).realpath
        puts "#{@watch_full}"


        @run = args[:exec].to_s

        @delay = args[:delay].to_i

        self.inform

    end

    def inform
        puts "Moar version 0.1".colorize(:light_white)
        print " * ".colorize(:light_red)
        puts "Checking every #{@delay} seconds"
        print " * ".colorize(:light_red)
        puts "Watching #{@watch} for changes"
        print " * ".colorize(:light_red)
        puts "Running #{@run} upon changes"
    end

    def onchange
        system("clear")
        system("#{@run}")
    end

    def timestamp

        File.mtime(@watch_full)

#        begin
#        File.mtime(@watch_full)
#
#        rescue Errno::ENOENT => e
#            puts "Err: Attempted timestamp-chk while file was being saved".colorize(:red)
#            puts "Running command in #{@delay} seconds..."
#            sleep delay
#
#            timestamp
#        end

    end

    def before
        @time_before = self.timestamp
    end

    def after
        @time_after = self.timestamp
    end

    def check
        if @time_before != @time_after
            self.onchange
        end
    end

end


main = Executor.new opts

while true
    main.before
    sleep main.delay
    main.after
    main.check
end
